image: python:3.6.5

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

pages:
  script:
  - pip install -U sphinx sphinx-rtd-theme
  - sphinx-build -b html docs/source/ public
  artifacts:
    paths:
    - public
  only:
  - develop
